name: 🚀 Feature Request
description: Suggest an idea for this plugin.
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Describe the solution you'd like
    validations:
      required: true
